#: --- UI Elements (Material 3) ---
cursor            #a8d293
cursor_text_color #153808

foreground            #e1e4da
background            #0c0f0a
selection_foreground  #273421
selection_background  #bccbb0
url_color             #a8d293

active_tab_foreground   #153808
active_tab_background   #a8d293
inactive_tab_foreground #c3efad
inactive_tab_background #2c4f1e

active_border_color   #a8d293
inactive_border_color #153808

#: --- Terminal Colors (Base16) ---

#: black
color0  #081812
color8  #4f5950

#: red
color1  #68706a
color9  #68706a

#: green
color2  #081712
color10 #081712

#: yellow
color3  #3f4c4f
color11 #3f4c4f

#: blue
color4  #0a1e1a
color12 #0a1e1a

#: magenta
color5  #0d2321
color13 #0d2321

#: cyan
color6  #152727
color14 #152727

#: white
color7  #7e857a
color15 #adb0a3

#: --- Optional Marks (Material 3) ---
mark1_foreground #052100
mark1_background #c3efad
mark2_foreground #131f0d
mark2_background #d8e7cb
mark3_foreground #002021
mark3_background #bbebed
