#: --- UI Elements (Material 3) ---
cursor            #00696e
cursor_text_color #ffffff

foreground            #161d1d
background            #ffffff
selection_foreground  #ffffff
selection_background  #4a6364
url_color             #00696e

active_tab_foreground   #ffffff
active_tab_background   #00696e
inactive_tab_foreground #002022
inactive_tab_background #9cf0f6

active_border_color   #00696e
inactive_border_color #ffffff

#: --- Terminal Colors (Base16) ---

#: black
color0  #ffffff
color8  #aab6b8

#: red
color1  #395458
color9  #395458

#: green
color2  #f9f9f8
color10 #f9f9f8

#: yellow
color3  #97a8a9
color11 #97a8a9

#: blue
color4  #ffffff
color12 #ffffff

#: magenta
color5  #ffffff
color13 #ffffff

#: cyan
color6  #fefefe
color14 #fefefe

#: white
color7  #728588
color15 #3a5459

#: --- Optional Marks (Material 3) ---
mark1_foreground #002022
mark1_background #9cf0f6
mark2_foreground #041f21
mark2_background #cce8e9
mark3_foreground #081b36
mark3_background #d6e3ff
