set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'jimeh/tmuxifier'
set -g @tmux-gruvbox 'dark'

setw -g mouse on

run '~/.tmux/plugins/tpm/tpm'
