PACKAGE_NAME="hotfix-kvadra-touchpad"
PACKAGE_VERSION="1.0"
BUILT_MODULE_NAME[0]="hotfix-kvadra-touchpad"
DEST_MODULE_LOCATION[0]="/extramodules/"
# MAKE[0]="make KERNELRELEASE=${kernelver}"
MAKE[0]="make KERNEL_DIR=/lib/modules/${kernelver}/build"
AUTOINSTALL="yes"
