general {
  ignore_empty_input = true
}

background {
  monitor =
  path = /home/luxluth/Pictures/walls/wallhaven-rqjmpj.jpg
}

input-field {
    monitor =
    size = 210, 50
    outline_thickness = 1
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = false
    dots_rounding = -1
    outer_color = rgba(00000000)
    inner_color = rgba(00000000)
    font_color = rgb(161d1d)
    # font_color = rgb(f4fafa)
    fade_on_empty = false
    fade_timeout = 1000
    placeholder_text = <b>パスワード</b>
    hide_input = false
    rounding = -1
    check_color = rgb(00696e)
    fail_color = rgb(ba1a1a)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false

    position = -30, -550
    halign = right
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date "+%I %M"
    text_align = left
    color = rgba(161d1dcc)
    # color = rgba(f4fafacc)
    font_size = 400
    font_family = DM Serif Text
    rotate = 0

    # position = -320, -100
    position = 0, -100
    halign = center
    valign = center
}

