local VARS = require("confs.variables")

hl.on("hyprland.start", function()
	hl.exec_cmd("hypridle")
	hl.exec_cmd("qs")
	hl.exec_cmd("fcitx5 -d")

	hl.exec_cmd(VARS.scriptsDir .. "/portal.fish")

	hl.exec_cmd(VARS.scriptsDir .. "/nvim.fish")
	hl.exec_cmd(VARS.scriptsDir .. "/rt")
	hl.exec_cmd(VARS.scriptsDir .. "/hd")
	hl.exec_cmd("hyprsunset")
	hl.exec_cmd("hyprctl setcursor Adwaita 24")
	hl.exec_cmd("awww-daemon & " .. VARS.scriptsDir .. "/bg.fish")
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
	hl.exec_cmd("gnome-keyring-daemon --start --components=pkcs11,secrets,ssh")
	hl.exec_cmd("seekr --silent")
	hl.exec_cmd("~/.cargo/bin/hyprshell run")
end)
