background {
    monitor =
    path = {{ image }}
}

input-field {
    monitor =
    size = 210, 50
    outline_thickness = 1
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = false
    dots_rounding = -1
    outer_color = rgba(00000000)
    inner_color = rgba(00000000)
    font_color = rgb({{ colors.on_surface.default.hex_stripped }})
    fade_on_empty = false
    fade_timeout = 1000
    placeholder_text = <b>パスワード</b>
    hide_input = false
    rounding = -1
    check_color = rgb({{ colors.primary.default.hex_stripped }})
    fail_color = rgb({{ colors.error.default.hex_stripped }})
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false

    position = -30, -550
    halign = right
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +%I
    text_align = left
    color = rgba({{ colors.on_background.default.hex_stripped }}cc)
    font_size = 80
    font_family = DM Serif Text
    rotate = 0

    position = 30, -440
    halign = left
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +%M
    text_align = left
    color = rgba({{ colors.on_background.default.hex_stripped }}cc)
    font_size = 80
    font_family = DM Serif Text
    rotate = 0

    position = 30, -530
    halign = left
    valign = center
}
